language: objective-c
osx_image: xcode10.2
before_install:
  - gem install cocoapods -v '1.5.0'
install:
  - ./install_swiftlint.sh
script:
  - gem install travis
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - xcodebuild clean build test -workspace Example/SwiftyHTML.xcworkspace -scheme SwiftyHTML-Example -destination "platform=iOS Simulator,name=iPhone X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint --allow-warnings